### PR TITLE
Fix/security issues

### LINKED ISSUE #5: Implement user mapping between MM and OpsGenie
Yes, I like this.  Let me summarize to see if we agree
- On successful configure by sysadmin the app will show its Settings.
- One of the settings is "Link users by email address" On/Off boolean, default = On
- The description of this setting says "Allow Mattermost users to update alerts in OpsGenie if their email in Mattermost matches their email in OpsGenie"
- If the switch is on then allow email user linking, and allow users with matching email addresses to update records in OpsGenie from Mattermost.  Also, allow users in Mattermost to subscribe channels to OpsGenie Notifications if they have the correct permissions in OpsGenie
- If the switch is off then the buttons shown on OpsGenie notifications will not be shown.  Only Sysadmins in Mattermost can Subscribe a channel to notifications from OpsGenie.

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/dgp3i5m417nxmq4ukxuee31jzr) *by @asatkinson*._

### PR DESCRIPTION
**Pull request by LizSegura98**
Fix [(Implement user mapping between MM and OpsGenie)](https://github.com/mattermost/mattermost-app-opsgenie/issues/5) issue:

- Link to issue: [(Implement user mapping between MM and OpsGenie)](https://github.com/mattermost/mattermost-app-opsgenie/issues/5)

- Thread to Github issue in Mattermost: [(Issue description)](https://community.mattermost.com/core/pl/yiitqc8c1pbrfkw5qjykpzb9we)

- Thread to first posible solutions: [(Posible solutions)](https://community.mattermost.com/core/pl/hqtkx5113pgg7df6bx7ikezwey)

### CODE REVIEW

**Comment by LizSegura98** [comment]
Open issue [(Implement user mapping between MM and OpsGenie)](https://github.com/mattermost/mattermost-app-opsgenie/issues/5) being fixed in  [(Fix/security issues)](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1/files)

File: src/types/mattermost.ts [hunk 1]
```diff
@@ -170,7 +170,7 @@ export type PostResponse = {
     root_id: string,
     original_id: string,
     message: string,
-    props: { attachments: Attachment[]; }
+    props: { attachments: Attachment[]; app_bindings: any[] }
```
Comment (mickmister) [inline src/types/mattermost.ts]:
```suggestion
    props: { attachments: Attachment[]; app_bindings: AppBinding[] }
```

File: src/types/functions.ts [hunk 2]
```diff
@@ -1,6 +1,5 @@
-import { AppCallAction, AppContext, AppContextAction, AppForm } from './apps';
-import { WebhookRequest } from './opsgenie';
+import { AppCallAction, AppContext, AppContextAction, AppForm, WebhookAppCallRequest } from './apps';
 
-export type WebhookFunction = (webhookRequest: WebhookRequest<any>, context: AppContext) => Promise<void>;
+export type WebhookFunction = (webhookRequest: WebhookAppCallRequest<any>) => Promise<void>;
```
Comment (mickmister) [inline src/types/functions.ts]:
```suggestion
export type WebhookFunction<T> = (webhookRequest: WebhookAppCallRequest<T>) => Promise<void>;
```

File: src/forms/list-alert.ts [hunk 3]
```diff
@@ -1,34 +1,70 @@
...
+    let alerts: Alert[] = await tryPromise<Alert[]>(opsGenieClient.listAlert(params), ExceptionType.MARKDOWN, i18nObj.__('forms.error'));
+
+    if (!allowMember) {
+        throw new Exception(ExceptionType.MARKDOWN, i18nObj.__('general.validation-user.genie-action-invalid'));
+    }
+
+    if (!isSystemAdmin) {
+        const teams: Teams[] = await getAllTeamsCall(call);
+        const teamsIds: string[] = teams.map((team) => team.id);
+        alerts = alerts.filter((alert: Alert) => teamsIds.includes(alert.ownerTeamId));
```
Comment (mickmister) [inline src/forms/list-alert.ts]: Are we able to provide the team IDs in the request to OpsGenie, rather than manually filtering them out here?

File: src/forms/create-alert.ts [hunk 4]
```diff
@@ -1,38 +1,45 @@
...
+
+    const team: Team = await tryPromise<Team>(opsGenieClient.getTeam(identifier), ExceptionType.MARKDOWN, i18nObj.__('forms.error'));
+
+    if (!allowMember) {
+        throw new Exception(ExceptionType.MARKDOWN, i18nObj.__('general.validation-user.genie-action-invalid'));
+    }
+
+    if (!isSystemAdmin) {
+        const teamMembers: string[] | undefined = team?.members?.map((member) => member.user.username);
+        if (!teamMembers || !teamMembers.includes(actingUser?.email || '')) {
```
Comment (mickmister) [inline src/forms/create-alert.ts]: `!teamMembers.includes('')` doesn't seem like a useful check. Will that ever be the case?

File: src/bindings/bindings.ts [hunk 5]
```diff
@@ -19,6 +19,7 @@ import {
     options_alert_time,
 } from '../constant';
 import { configureI18n } from '../utils/translations';
+import { ExtendRequired } from '../utils/user-mapping';
```
Comment (mickmister) [inline src/bindings/bindings.ts:22]: Should this be `ExpandRequired`?

File: src/api/webhook.ts [hunk 6]
```diff
@@ -23,16 +23,15 @@ const WEBHOOKS_ACTIONS: { [key: string]: WebhookFunction } = {
 };
 
 export const incomingWebhook = async (request: Request, response: Response) => {
-    const webhookRequest: WebhookRequest<any> = request.body.values;
-    const context: AppContext = request.body.context;
+    const webhookRequest: WebhookAppCallRequest<any> = request.body;
```
Comment (mickmister) [inline src/api/webhook.ts]: Can we provide something more meaningful than `any` here?

File: src/api/help.ts [hunk 7]
```diff
@@ -26,44 +26,41 @@ function getHeader(context: AppContext): string {
...
         commands.push(addBulletSlashCommand(i18nObj.__('api.help.command-unack-command', { command: Commands.ALERT, unack: Commands.UNACK }), i18nObj.__('api.help.command-unack-description')));
         commands.push(addBulletSlashCommand(i18nObj.__('api.help.command-assign-command', { command: Commands.ALERT, assign: Commands.ASSIGN }), i18nObj.__('api.help.command-assign-description')));
         commands.push(addBulletSlashCommand(i18nObj.__('api.help.command-close-command', { command: Commands.ALERT, close: Commands.CLOSE }), i18nObj.__('api.help.command-close-description')));
         commands.push(addBulletSlashCommand(i18nObj.__('api.help.command-own-command', { command: Commands.ALERT, own: Commands.OWN }), i18nObj.__('api.help.command-own-description')));
         commands.push(addBulletSlashCommand(i18nObj.__('api.help.command-priority-command', { command: Commands.ALERT, priority: Commands.PRIORITY }), i18nObj.__('api.help.command-priority-description')));
+        commands.push(addBulletSlashCommand(i18nObj.__('api.help.command-list-alert-command', { command: Commands.ALERT, list: Commands.LIST }), i18nObj.__('api.help.command-alert-decription')));
```
Comment (mickmister) [inline src/api/help.ts:62]:
```suggestion
        commands.push(addBulletSlashCommand(i18nObj.__('api.help.command-list-alert-command', { command: Commands.ALERT, list: Commands.LIST }), i18nObj.__('api.help.command-alert-description')));
```

File: src/forms/settings.ts [hunk 8]
```diff
@@ -0,0 +1,69 @@
...
+
+    const oauthApp: Oauth2App = {
+        client_id: oauth2.client_id,
+        client_secret: oauth2.client_secret,
+        data: {
+            settings: {
+                link_email_address: linkEmailAddress,
+            },
+        },
+    };
```
Comment (mickmister) [inline src/forms/settings.ts:83]: I'm not sure if this belongs in the `Oauth2App` type, but it's sort of arbitrary I suppose. I would think the `Oauth2App` type is purely for authenticating, and not for application-level settings like `link_email_address`

File: src/restapi/middleware.ts [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+        res.json(showMessageToMattermost(new Exception(ExceptionType.TEXT_ERROR, i18nObj.__('general.validation-user.system-admin'))));
+        return;
+    }
+
+    next();
+};
+
+export const requireOpsGenieAPIKey = (req: Request, res: Response, next: () => void) => {
+    const call: AppCallRequest = req.body as AppCallRequest;
+    const oauth2: Oauth2App = call.context.oauth2 as Oauth2App;
```
Comment (mickmister) [inline src/restapi/middleware.ts]: Required: This may be `undefined` right?

File: src/forms/subscription-delete.ts [hunk 10]
```diff
@@ -1,47 +1,49 @@
...
-        api_key: configStore.opsgenie_apikey,
-    };
-    const opsGenieClient: OpsGenieClient = new OpsGenieClient(optionsOps);
+        const teams: Teams[] = await getAllTeamsCall(call);
+        const teamsIds: string[] = teams.map((team) => team.id);
+
+        if (!teamsIds.includes(opsSubscription.ownerTeam.id)) {
+            throw new Exception(ExceptionType.MARKDOWN, i18nObj.__('binding.binding.command-delete-no-found'));
+        }
+    }
```
Comment (mickmister) [inline src/forms/subscription-delete.ts]: Required: Are we checking the acting user's membership of the teams here?

File: src/utils/user-mapping.ts [hunk 11]
```diff
@@ -0,0 +1,109 @@
...
+    const oauth2: Oauth2App = call.context.oauth2 as Oauth2App;
+    return oauth2.client_id;
+}
+
+export function linkEmailAddress(oauth2App: Oauth2App | undefined): boolean {
+    const linkEmail = oauth2App?.data?.settings?.link_email_address;
+    return typeof linkEmail === 'boolean' ?
+        linkEmail :
+        true;
+}
```
Comment (mickmister) [inline src/utils/user-mapping.ts:26]: Nice approach

File: src/utils/user-mapping.ts [hunk 12]
```diff
@@ -0,0 +1,109 @@
...
+        throw new Exception(ExceptionType.MARKDOWN, i18nObj.__('general.validation-user.genie-action-invalid'));
+    }
+
+    if (!isSystemAdmin) {
+        const teamIdentifier: Identifier = {
+            identifier: alertResponse.ownerTeamId,
+            identifierType: IdentifierType.ID,
+        };
+
+        const team: Team = await tryPromise<Team>(opsGenieClient.getTeam(teamIdentifier), ExceptionType.MARKDOWN, i18nObj.__('forms.error'));
```
Comment (mickmister) [inline src/utils/user-mapping.ts]: Is it possible we don't get all of the team members due to paging?

File: src/forms/settings.ts (hunk 8 above)
Comment (LizSegura98) [reply src/forms/settings.ts:83]: In that case, we should store this configuration (like `link_email_address`) directly on KVStore?

File: src/bindings/bindings.ts (hunk 5 above)
Comment (LizSegura98) [reply src/bindings/bindings.ts:22]: Sorry, didn't understand the question

File: src/forms/subscription-delete.ts (hunk 10 above)
Comment (LizSegura98) [reply src/forms/subscription-delete.ts]: No, only regular members. System admin users are not email validated

File: src/types/mattermost.ts (hunk 1 above)
Comment (LizSegura98) [reply src/types/mattermost.ts]: This was solved in commit [d91fc61](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1/commits/d91fc61f3d5c4e7a5418a74cce2c5a72c991a951)

File: src/types/functions.ts (hunk 2 above)
Comment (LizSegura98) [reply src/types/functions.ts]: This was solved in commit [d91fc61](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1/commits/d91fc61f3d5c4e7a5418a74cce2c5a72c991a951)

File: src/forms/create-alert.ts (hunk 4 above)
Comment (LizSegura98) [reply src/forms/create-alert.ts]: This was solved in commit [d91fc61](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1/commits/d91fc61f3d5c4e7a5418a74cce2c5a72c991a951)

File: src/api/webhook.ts (hunk 6 above)
Comment (LizSegura98) [reply src/api/webhook.ts]: This was solved in commit [d91fc61](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1/commits/d91fc61f3d5c4e7a5418a74cce2c5a72c991a951)

File: src/restapi/middleware.ts (hunk 9 above)
Comment (LizSegura98) [reply src/restapi/middleware.ts]: This was solved in commit [d91fc61](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1/commits/d91fc61f3d5c4e7a5418a74cce2c5a72c991a951)

File: src/utils/user-mapping.ts (hunk 12 above)
Comment (LizSegura98) [reply src/utils/user-mapping.ts]: On OpsGenie documentation [GET Team](https://docs.opsgenie.com/docs/team-api#get-team), there is nothing about team members being paginated

File: src/forms/list-alert.ts (hunk 3 above)
Comment (LizSegura98) [reply src/forms/list-alert.ts]: Currently OpsGenie query alert can only filter by a team at time [(Search queries for alerts)](https://support.atlassian.com/opsgenie/docs/search-queries-for-alerts/).

teams : team1 | Name of the team.
-- | --

We tried to add more, but the response array is returned as empty

File: src/forms/configure-admin-account.ts [hunk 13]
```diff
@@ -58,14 +51,13 @@ export async function opsGenieConfigForm(call: AppCallRequest): Promise<AppForm>
...
     const values: AppCallValues = <any>call.values;
     const i18nObj = configureI18n(call.context);
-    const actingUser: AppActingUser = call.context.acting_user!;
-
-    if (!isUserSystemAdmin(actingUser)) {
-        throw new Exception(ExceptionType.MARKDOWN, i18nObj.__('forms.configure-admin.system-admin'));
-    }
+    const linkEmailAddress: boolean = typeof oauth2.data?.settings?.link_email_address === 'boolean' ?
+        oauth2.data?.settings.link_email_address :
+        true;
```
Comment (srkgupta) [inline src/forms/configure-admin-account.ts]: We are restricting the option to view Configs only to System Admins. However we have removed the restriction while submitting OpsGenie config to all OpsGenie members. This does not makes sense. We should add these restrictions again and restrict view & update configurations only to System Admins.

File: src/forms/take-ownership-alert.ts [hunk 14]
```diff
@@ -1,81 +1,61 @@
...
-    const alert: Alert = responseAlert.data;
-    const alertURL: string = await getAlertLink(alertTinyId, alert.id, opsGenieClient);
+    const alert: Alert = await canUserInteractWithAlert(call, alertTinyId);
+    const alertURL: string = await getAlertLink(alertTinyId, alert.id, opsGenieClient, call.context.mattermost_site_url, call.context.app_path);
 
-    if (alert.owner === mattermostUser.email) {
-        throw new Exception(ExceptionType.MARKDOWN, i18nObj.__('forms.actions.exception-owner', { alert: alertURL }));
+    if (alert.owner === actingUser.email) {
+        throw new Exception(ExceptionType.MARKDOWN, i18nObj.__('forms.actions.exception-owner', { alert: alertURL }), call.context.mattermost_site_url, call.context.app_path);
     }
```
Comment (srkgupta) [inline src/forms/take-ownership-alert.ts:54]: Missing check `canUserInteractWithAlert`

File: src/forms/unack-alert.ts [hunk 15]
```diff
@@ -3,62 +3,53 @@ import {
...
-
     const optionsOpsgenie: OpsGenieOptions = {
-        api_key: config.opsgenie_apikey,
+        api_key: apiKey,
     };
     const opsGenieClient = new OpsGenieClient(optionsOpsgenie);
 
+    const alert: Alert = await canUserInteractWithAlert(call, alertTinyId);
+    const alertURL: string = await getAlertLink(alertTinyId, alert.id, opsGenieClient, call.context.mattermost_site_url, call.context.app_path);
+
```
Comment (srkgupta) [inline src/forms/unack-alert.ts:43]: Similarly missing check `canUserInteractWithAlert`

**Review by srkgupta — CHANGES_REQUESTED** [review]
Thanks @liz-segura98. The overall changes LGTM. Great work here. Just added few observations.

File: src/forms/unack-alert.ts (hunk 15 above)
Comment (LizSegura98) [reply src/forms/unack-alert.ts:43]: The check in `canUserInteractWithAlert` is inside the function, if a user has no access to it, an exception will stop the request, but if the user has access, the alert will be return

File: src/forms/take-ownership-alert.ts (hunk 14 above)
Comment (LizSegura98) [reply src/forms/take-ownership-alert.ts:54]: The check is in line `44`, before performing any action to an alert, we validate with:
`const alert: Alert = await canUserInteractWithAlert(call, alertTinyId);`

File: src/forms/configure-admin-account.ts (hunk 13 above)
Comment (LizSegura98) [reply src/forms/configure-admin-account.ts]: We removed the validation because it was moved to middleware section, but I will also add it to the flow again, so we can have double validation on that

Comment (LizSegura98) [reply src/forms/configure-admin-account.ts]: Done, this was fixed in [f990168](https://github.com/liz-segura98/mattermost-app-opsgenie/pull/1/commits/f9901682b0106aa464f620e3f35761d3a051d273)
